name: Alpine Test
on: push

jobs:
  alpine-local-verbose:
    name: Local Install - Verbose (Alpine)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh -i
      - name: Perform Installation
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh -v
  alpine-local-normal:
    name: Local Install - Normal (Alpine)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh -i
      - name: Perform Installation
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh
  alpine-local-quiet:
    name: Local Install - Quiet (Alpine)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh -i
      - name: Perform Installation
        run: |
          docker run -v $(pwd):/root/dots alpine sh /root/dots/install.sh -q

  alpine-remote-verbose:
    name: Remote Install - Verbose (Alpine)
    runs-on: ubuntu-latest
    steps:
      - name: Installation Info
        run: |
          cat install.sh | docker run -v $(pwd):/root/dots alpine sh -s -- -i
      - name: Perform Installation
        run: |
          cat install.sh | docker run -v $(pwd):/root/dots alpine sh -s -- -y
