name: MacOS Test
on: push

jobs:
  macos-local-verbose:
    name: Local Install - Verbose (MacOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          sh install.sh -i
      - name: Perform Installation
        run: |
          sh install.sh -v
  macos-local-normal:
    name: Local Install - Normal (MacOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          sh install.sh -i
      - name: Perform Installation
        run: |
          sh install.sh
  macos-local-quiet:
    name: Local Install - Quiet (MacOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation Info
        run: |
          sh install.sh -i
      - name: Perform Installation
        run: |
          sh install.sh -q

  macos-remote-verbose:
    name: Remote Install - Verbose (MacOS)
    runs-on: macos-latest
    steps:
      - name: Installation Info
        run: |
          sh -c "$(curl -sSL git.io/Jt8w0)" - -i
      - name: Perform Installation
        run: |
          sh -c "$(curl -sSL git.io/Jt8w0)" - -v
