name: Shell Check
on: push

jobs:
  shellcheck:
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: zsh
      - name: Ban echo
        run: |
          ! grep 'echo' install.sh
